fix

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -102,6 +102,15 @@ jobs:
           mvn versions:set -DnewVersion=${{ needs.bump.outputs.major_version }}.${{ needs.bump.outputs.minor_version }}.${{ needs.bump.outputs.build_version }} -DgenerateBackupPoms=false
       - name: Build and verify with Maven 🔨
         run: mvn --batch-mode --update-snapshots verify $MAVEN_ARGS
+      - name: List signed files 🐞
+        run: |
+          echo "📦 Contents of target/:"
+          ls -lh target/
+          echo ""
+          echo "🔍 GPG signatures:"
+          find target/ -type f -name "*.asc" -exec echo "✔ Found:" {} \;
+          echo ""
+          echo "❓ Missing POM signature?" && test ! -f target/*pom.asc && echo "❌ No POM signature found!" || echo "✅ POM is signed."      
       - name: Publish to Maven Central
         run: mvn verify central-publishing:publish -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} $MAVEN_ARGS
         env:
